### PR TITLE
Quiz 15 for async-await

### PR DESCRIPTION
**Pull request by alayek**
Have kept the quizzes in tandem with Examples in Promises. Should I include some real life examples, like file opening etc.?

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks for this! I hope you don't mind me merging this and making a few changes? I've really appreciated all the help you've given me on these! You've saved me a lot of time! I'm really looking forward to using these next week!

**Comment by alayek** [comment]
Sure! Feel free to make changes as you see fit.

I was only hoping we would have some real examples involving API requests, or file systems related. I have used Async Await extensively with Selenium Webdriver - makes it such a breeze to write and maintain those page objects.

**Comment by kentcdodds** [comment]
Totally, practical examples are useful. But I find that they _can sometimes_ distract from the learning experience when someone's initially exposed to the feature. So for the quizzes, contrived examples are great. Practical examples are good for the tests. Though I wouldn't actually want to make database calls in the tests either. So I'm thinking that having a companion app to this workshop could be useful. I'm still thinking about that.

Thanks again for all the help!

**Comment by alayek** [comment]
@kentcdodds I like the [2048 app](https://github.com/gabrielecirulli/2048). Pure ES5, no external libraries, supported across all major desktop and mobile browsers.

IMHO it's perfect candidate for using it as an example to refactor ES5 codebase to ES6. Although, I don't think all ES6 related features would be required. But students would get hands on experience on how to migrate something from ES5 to ES6.

Is this something you have been looking for?

**Comment by kentcdodds** [comment]
Ah, interesting idea. Taking an existing app and migrating it. Actually, the first time I gave this workshop, I gave it in two parts. The morning was this workshop (the tests) and the afternoon was migrating the ES5 TodoMVC app to ES6 with webpack (most of the time was spent learning and configuring webpack). Since then, I've split the two workshops because they're both pretty significant subjects on their own. You can see the webpack workshop [here](https://github.com/kentcdodds/es6-todomvc).

That said, I think more people would be interested in 2048. I remember that was really hot when it came out. I even made [my own fork](https://github.com/kentcdodds/2048) to add authentication :) ([It still works!](https://kentcdodds.github.io/2048/))

Also, I blame you for reminding me! But I won again on my first try!

screen shot 2017-01-17 at 10 44 16 am

**Comment by alayek** [comment]
Your webpack workshop was the first workshop that got me into your orbit 😄 

I was desperately searching for a non-react example of Webpack setup, preferably with Vanilla JS. And I came across your egghead course. I cannot afford a pro account, but the free video had link to your GitHub repo.

I went through the commits reverse chronically. It was really cool!

Thanks for the amazing work. At the risk of repeating myself, I have indeed learned a lot from your work. ✨

**Pull request merged**
